modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/shedaniel/architectury/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "architectury_registrybiomes"
version = "${version}"
displayName = "Architectury (registryBiomes)"
authors = "shedaniel"
description = '''
Split off of Architectury (registry) due to dependencies.
'''
logoFile = "icon.png"
license = "LGPL-3"

[[dependencies.architectury_registrybiomes]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_registrybiomes]]
modId = "neoforge"
type = "required"
versionRange = "[20.6.98-beta,)"
ordering = "NONE"
side = "BOTH"