modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/shedaniel/architectury/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "architectury_annotations"
version = "${version}"
displayName = "Architectury Annotations"
authors = "shedaniel"
description = '''
Annotations provided by Architectury API
'''
logoFile = "icon.png"
license = "LGPL-3"

[[dependencies.architectury_annotations]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_annotations]]
modId = "neoforge"
type = "required"
versionRange = "[20.6.98-beta,)"
ordering = "NONE"
side = "BOTH"