modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/shedaniel/architectury/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "architectury_legacyitems"
version = "${version}"
displayName = "Architectury (legacyItems)"
authors = "shedaniel"
description = '''
'''
logoFile = "icon.png"
license = "LGPL-3"

[[dependencies.architectury_legacyitems]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_legacyitems]]
modId = "neoforge"
type = "required"
versionRange = "[20.6.98-beta,)"
ordering = "NONE"
side = "BOTH"