modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/shedaniel/architectury/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "architectury_legacyextensions"
version = "${version}"
displayName = "Architectury (legacyExtensions)"
authors = "shedaniel"
description = '''
Deprecated interface injections.
'''
logoFile = "icon.png"
license = "LGPL-3"

[[dependencies.architectury_legacyextensions]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_legacyextensions]]
modId = "neoforge"
type = "required"
versionRange = "[20.6.98-beta,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "architectury-legacyExtensions.mixins.json"